# Local dev (commented out)
 spring.datasource.url=jdbc:postgresql://localhost:5432/wallclubs
 spring.datasource.username=postgres
 spring.datasource.password=root@123

# Render prod (hardcoded)
#spring.datasource.url=jdbc:postgresql://dpg-cut3pr5svqrc73e41120-a.singapore-postgres.render.com/wallclubs_db
#spring.datasource.username=wallclubs_db_user
#spring.datasource.password=9wxxLuRyQvG9bUyIMSI7BqoqVDyJEm0R
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache=false
server.port=${PORT:8080}